version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "3306:3306"

  migrate:
    build: ./docker/migrate
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    command: >
      sh -c "/code/wait_db.sh &&
      migrate -path migrations -database mysql://root:password@tcp\(db:3306\)/test up"
